services:
  db:
    # 1. Reproducibilidad: Fija la versión de la imagen
    image: postgres:15-alpine # Usamos alpine para una imagen más ligera

    # 2. Seguridad: Usa variables del archivo .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # PGDATA se usa para asegurar que Postgres use el directorio correcto dentro del contenedor
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      # Montamos el volumen en el subdirectorio definido por PGDATA
      - pgDataV2:/var/lib/postgresql/data/pgdata

    ports:
      # Usamos la variable de entorno para el puerto también
      - '${DB_PORT}:5432'

    # 3. Robustez: Política de reinicio y chequeo de salud
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    # Tus optimizaciones de rendimiento
    shm_size: 1gb
    mem_limit: 1g
    command: postgres
      -c shared_buffers=256MB
      -c work_mem=4MB
      -c maintenance_work_mem=64MB
      -c max_connections=40
      -c effective_cache_size=512MB
      -c logging_collector=on
      -c log_destination=stderr
      -c log_statement=ddl

  minio:
    image: 'quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z'
    ports:
      - '${MINIO_PORT}:9000' # Puerto para la API de S3
      - '${MINIO_CONSOLE_PORT}:9001' # Puerto para la consola web
    command: server /data --console-address ":9001"
    environment:
      # Credenciales de acceso root. La contraseña debe tener al menos 8 caracteres.
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data

    # --- CORRECCIÓN AQUÍ ---
    # Le decimos a MinIO que inicie el servidor, dónde guardar los datos (/data)
    # y en qué dirección exponer la consola web.

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    mem_limit: 1g

  createbuckets:
    image: quay.io/minio/mc:RELEASE.2025-03-12T17-29-24Z
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb minio/nest-images/some-directory;
      /usr/bin/mc mb minio/nest-images;
      exit 0;
      "

volumes:
  pgDataV2:
    # Es buena práctica definir el volumen como externo o nombrarlo explícitamente
    name: postgres_data_v2
  minio_data:
    name: minio_data
